spring:
  datasource:
    url: jdbc:postgresql://localhost:6969/timairport_db
    username: postgres
    password: Test1234=
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"